services:
  db:
    image: postgres:16
    container_name: vistorias_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vistorias
    ports:
      - "5050:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
